window.TransportContent = {
  da: {
    road: {
      kicker: "01 · Landevej",
      title: "Landevej",
      lead: "Fleksibel distribution i Europa — dør-til-dør med høj frekvens og klar plan.",
      pros: [
        "Dør-til-dør uden omlastning — lav håndteringsrisiko",
        "Høj frekvens og korte forløb på opstartstiden",
        "Bred materielvifte fra varebil til specialtrailer",
        "Stærk på kortere og mellemlange europæiske strækninger",
        "Nem at tilpasse, hvis planen ændrer sig undervejs",
      ],
      cons: [
        "Afhængig af kørsels-/hviletid, trafik og vejr",
        "Begrænset kapacitet pr. enhed (typisk 24 t / 33 paller)",
        "Højere CO₂-aftryk pr. ton-km end sø og rail",
        "Grænsekontrol og specialgods kan kræve ADR/tilladelser",
      ],
      equipmentIntro: "Fra standard 13,6 m curtain-trailer til specialtrailere til projektgods og tungt maskinel.",
      equipment: [
        {
          id: "road-curtain",
          name: "Trækker + 13,6 m curtain-trailer",
          specs: "24.000 kg · 33 EUR-paller · lift/ADR",
          lead: "Europas arbejdshest — åben/lukket presenning, læsbar fra side og bag.",
          details: [
            ["Indv. mål", "13,60 × 2,47 × 3,10 m"],
            ["Læssevægt", "op til 24.000 kg"],
            ["Paller", "33 EUR-paller (1 lag)"],
            ["Ekstra", "Lift, ADR, coil-well kan aftales"],
          ],
          goodFor: ["Stykgods og fuld last (LTL/FTL)", "Paller, kasser, ruller og lange emner", "Sidelæsning med truck eller kran"],
          notes: ["Højdebegrænsning ved bro-/tunnelpassager på visse ruter", "Ikke temperaturstyret"],
        },
        {
          id: "road-solo18",
          name: "Solobil 18 t",
          specs: "7.000 kg · 23 EUR-paller · lift/ADR",
          lead: "Kompakt enhedsvogn til by- og mellemdistancer uden trailer-kobling.",
          details: [
            ["Indv. mål", "9,40 × 2,45 × 2,90 m"],
            ["Læssevægt", "ca. 7.000 kg"],
            ["Paller", "23 EUR-paller"],
            ["Ekstra", "Lift, ADR"],
          ],
          goodFor: ["Leverancer i bymidter med pladsbegrænsning", "Distribution med flere stop", "Når der er behov for lift"],
          notes: ["Lavere nyttelast end semitrailer", "Kan kræve miljøzone-godkendelse i visse byer"],
        },
        {
          id: "road-solo75",
          name: "Solobil 7,5 t",
          specs: "3.500 kg · 15 EUR-paller · lift/ADR",
          lead: "Let distributionsbil — nem at manøvrere og oftest uden særlige certifikater.",
          details: [
            ["Indv. mål", "6,20 × 2,45 × 2,60 m"],
            ["Læssevægt", "ca. 3.500 kg"],
            ["Paller", "15 EUR-paller"],
            ["Ekstra", "Lift, ADR"],
          ],
          goodFor: ["Hurtig bydistribution", "Små til mellem forsendelser", "Trange gader og afhentningssteder"],
          notes: ["Ikke ideel til lange eller høje emner"],
        },
        {
          id: "road-van",
          name: "Varebil 3,5 t",
          specs: "700–1.200 kg · 5–10 EUR-paller · lift/ADR",
          lead: "Smidig og hurtig — velegnet til ekspres og mindre forsendelser.",
          details: [
            ["Typer", "Firanka 4,2–4,9 m · Box 3,85–4,70 m"],
            ["Højde", "2,00–2,60 m indvendig"],
            ["Læssevægt", "700–1.200 kg"],
            ["Paller", "5–10 EUR-paller"],
          ],
          goodFor: ["Ekspres- og samme-dags kørsel", "Tidskritiske pharma- og reservedelsforsendelser", "Dedikeret direkte kørsel"],
          notes: ["Begrænset kapacitet pr. enhed"],
        },
        {
          id: "road-reefer",
          name: "Køl-/frysetrailer",
          specs: "22.000 kg · 13,6 × 2,45 × 2,65 m · temp.styret · ADR",
          lead: "Temperaturstyret transport — fra dyb frost til pharma-vinduer.",
          details: [
            ["Indv. mål", "13,60 × 2,45 × 2,65 m"],
            ["Temperatur", "−25 °C til +25 °C"],
            ["Agregat", "Dieselagregat med monitorering"],
            ["Standarder", "ATP, FRC/FNA efter gods"],
          ],
          goodFor: ["Fødevarer, medicin, blomster", "Temperatur-kritiske forsendelser", "Multi-temp-opdelinger efter aftale"],
          notes: ["Højere drifts- og brændstofomkostninger", "Kræver ren kølekæde og dokumentation"],
        },
        {
          id: "road-platform",
          name: "Platform / flak",
          specs: "24.000 kg · 13,6 m · til stål, kontainere og byggemateriale",
          lead: "Åben platform — læs fra alle sider og ovenfra med kran eller truck.",
          details: [
            ["Længde", "13,60 m (standard)"],
            ["Læssevægt", "op til 24.000 kg"],
            ["Udstyr", "Pasning af stål-coils, pæle, pulver"],
            ["Sikring", "Stropper, kæder, spæntræ"],
          ],
          goodFor: ["Stål, rør, kontainere, byggemateriale", "Kran- eller sideløftning", "Overbrede emner med pilotbil"],
          notes: ["Ingen beskyttelse mod vejr — afhængig af emballage"],
        },
        {
          id: "road-tiefbett",
          name: "Tiefbett / lowbed",
          specs: "38.000 kg · niedrig bed · til høje maskiner og industrielementer",
          lead: "Sænket lad til ekstra højde — bygget til maskiner og industrielementer.",
          details: [
            ["Læssevægt", "op til 38.000 kg"],
            ["Nicke-højde", "ca. 0,85 m over vej"],
            ["Udvidelse", "Afkoblelig front, udskud til bredde"],
            ["Eskorte", "Pilotbil ved over-mål"],
          ],
          goodFor: ["Høje maskiner, tanke, industrielementer", "Ekstrem tung last", "Projekt- og anlægstransport"],
          notes: ["Tilladelser og ruteplanlægning er afgørende", "Tidsvinduer kan være restriktive"],
        },
        {
          id: "road-semi",
          name: "Semi-lowloader",
          specs: "28.000 kg · hydrauliske ramper · til gravemaskiner og tungt grej",
          lead: "Lavbed med hydraulisk indkøring — på og af på få minutter.",
          details: [
            ["Læssevægt", "op til 28.000 kg"],
            ["Ramper", "Hydrauliske med wirespil"],
            ["Udstyr", "Spæntræ, surringspunkter"],
            ["Eskorte", "Efter emnets mål"],
          ],
          goodFor: ["Gravemaskiner, entreprenørmateriel", "Bil- og maskintransport på hjul", "Relokering af tungt grej"],
          notes: ["Visse ruter kan kræve forhåndsgodkendelse"],
        },
        {
          id: "road-tele",
          name: "Tele / udtrækstrailer",
          specs: "22.000 kg · forlænges op til 21 m · til lange elementer",
          lead: "Udtrækstrailer til lange emner — skinner, mastesektioner, rotorblade.",
          details: [
            ["Længde", "Fra 13,6 m op til 21 m"],
            ["Læssevægt", "op til 22.000 kg"],
            ["Udstyr", "Oftest styreaksel til manøvrering"],
            ["Eskorte", "Pilotbil og sikkerhedskøretøj"],
          ],
          goodFor: ["Vindmøllevinger, master, skinner", "Lange præfabrikerede elementer", "Projektgods"],
          notes: ["Stor svingradius — krav til vejnet"],
        },
      ],
    },
    sea: {
      kicker: "02 · Sø",
      title: "Sø",
      lead: "Robust og omkostningseffektiv til volumen — FCL, LCL og specialcontainere.",
      pros: [
        "Lavest pris pr. ton på volumen og lange distancer",
        "Global kapacitet og ruter til stort set alle markeder",
        "Specialløsninger til overbredt, højt, tungt og temperaturstyret gods",
        "Lavt CO₂-aftryk pr. ton-km",
        "Skalerer fra stykgods (LCL) til fulde containere (FCL)",
      ],
      cons: [
        "Lang transittid — ofte uger frem for dage",
        "Stramme cut-offs og dokumentkrav før afgang",
        "ETA-variation pga. vejr, havne og kaj-kapacitet",
        "Specialgods kræver korrekt stuvning og emballage",
      ],
      equipmentIntro: "Vi booker og koordinerer alle gængse containertyper — og finder specialudstyr til det der ikke passer i en standard.",
      equipment: [
        {
          id: "sea-dry20",
          name: "20' Dry container",
          specs: "Indv. ca. 5,9 × 2,35 × 2,39 m · ~28 t · tørlast",
          lead: "Standard 20-fods container — arbejdshesten i FCL-verdenen.",
          details: [
            ["Indv. mål", "5,90 × 2,35 × 2,39 m"],
            ["Dør-åbning", "2,34 × 2,28 m"],
            ["Maks. last", "~28.000 kg (rute-afhængigt)"],
            ["Volumen", "~33 m³"],
          ],
          goodFor: ["Tungt, tæt stuvet gods", "Fuld container-last (FCL)", "Tørlast uden klimakrav"],
          notes: ["Lavere rumfang end 40'", "Ikke egnet til overhøjt gods"],
        },
        {
          id: "sea-dry40",
          name: "40' Dry container",
          specs: "Indv. ca. 12,03 × 2,35 × 2,39 m · ~28 t · tørlast",
          lead: "Dobbelt længden — optimal når volumen betyder mere end vægt.",
          details: [
            ["Indv. mål", "12,03 × 2,35 × 2,39 m"],
            ["Dør-åbning", "2,34 × 2,28 m"],
            ["Maks. last", "~28.000 kg"],
            ["Volumen", "~67 m³"],
          ],
          goodFor: ["Volumetunge laster", "Møbler, tekstil, non-food", "Fuld container-last (FCL)"],
          notes: ["Højde samme som 20' dry — ikke til overhøjt"],
        },
        {
          id: "sea-hc",
          name: "40' High cube (HC)",
          specs: "Ekstra højde 2,69 m indv. · til volumetungt gods",
          lead: "Samme bredde og længde som 40' dry, men ekstra højde til volumen.",
          details: [
            ["Indv. højde", "2,69 m (vs. 2,39 m på standard)"],
            ["Indv. længde/bredde", "12,03 × 2,35 m"],
            ["Maks. last", "~28.000 kg"],
            ["Volumen", "~76 m³"],
          ],
          goodFor: ["Letvægts- og volumetunge laster", "Høje emner op til 2,69 m", "Møbler, skum, isolering"],
          notes: ["Højdekrav på land-transport til/fra havn"],
        },
        {
          id: "sea-reefer",
          name: "Reefer 20'/40'",
          specs: "Temp.styret −30 °C til +30 °C · pharma, food, perishables",
          lead: "Temperaturstyret container — fra dyb frost til pharma-vinduer.",
          details: [
            ["Temperatur", "−30 °C til +30 °C"],
            ["Indv. mål 40' HC reefer", "11,56 × 2,29 × 2,56 m"],
            ["Strøm", "Ombord eller plug-in i havn"],
            ["Monitorering", "Datalogger og alarm"],
          ],
          goodFor: ["Frugt, grønt, fisk, kød", "Pharma og life science", "Temperatur-kritisk kemi"],
          notes: ["Plug-in-tid i havn skal bookes", "Kræver ren kølekæde"],
        },
        {
          id: "sea-opentop",
          name: "Open top",
          specs: "Åben top m/presenning · til overhøje emner og ovenfra-læsning",
          lead: "Container uden tag — læs fra oven med kran, sejl på som tag.",
          details: [
            ["Indv. mål 40'", "12,03 × 2,35 × 2,35 m"],
            ["Top", "Presenning-system med bøjler"],
            ["Maks. last", "~28.000 kg"],
            ["Ekstra højde", "Overhøjt kan aftales"],
          ],
          goodFor: ["Maskiner og emner med overhøjde", "Kranløft direkte i container", "Emner der ikke kan læsses fra døren"],
          notes: ["Vejr-udsathed uden hård top", "Kan kræve over-mål-godkendelse"],
        },
        {
          id: "sea-flatrack",
          name: "Flat rack",
          specs: "Uden sider/tag · til overbredt gods, maskiner og stål",
          lead: "Platform med gavlender — sider foldes ned, så ingen dimensions-grænse udover vægt.",
          details: [
            ["Standardlængder", "20' og 40'"],
            ["Maks. last", "op til 40.000 kg (40')"],
            ["Surring", "Stropper, kæder i platformen"],
            ["Gavlender", "Foldes ned for overlængde"],
          ],
          goodFor: ["Overbredde og overlange emner", "Bilfragt, maskiner, rør, stål", "Kranløft i/af havn"],
          notes: ["Ingen vejrbeskyttelse", "Surring er kritisk"],
        },
        {
          id: "sea-platform",
          name: "Platform",
          specs: "Fladt dæk uden ender · til særligt lange eller tunge emner",
          lead: "Helt fladt dæk uden sider og gavlender — kun til emner der ikke passer andre steder.",
          details: [
            ["Længder", "20' og 40'"],
            ["Maks. last", "Op til 40.000 kg"],
            ["Form", "Fladt — ingen gavle, ingen sider"],
            ["Surring", "Alle kanter"],
          ],
          goodFor: ["Ekstremt tunge/lange emner", "Industrielle komponenter", "Projekt- og anlægstransport"],
          notes: ["Bookes som over-dimensions (OOG)", "Kræver samme-høj stuvning i skib"],
        },
        {
          id: "sea-goh",
          name: "GOH (Garments on Hangers)",
          specs: "Integreret bøjlesystem · til konfektion uden ompakning",
          lead: "40' container med indbygget bøjle-system — tøj hænger færdigt fra fabrik til butik.",
          details: [
            ["Kapacitet", "op til 10.000–14.000 plagg"],
            ["System", "Faste/mobile stænger langs loftet"],
            ["Sikring", "Særlige bøjler og presenninger"],
            ["Basis", "40' dry eller HC"],
          ],
          goodFor: ["Fashion og konfektion", "High-end brands uden ompakning", "Direkte butiksleverance"],
          notes: ["Højere fragtpris pr. kg end standard", "Kun enkelte operatører tilbyder GOH"],
        },
      ],
    },
    air: {
      kicker: "03 · Luft",
      title: "Luft",
      lead: "Når tid er kritisk — hurtige afgange, cut-offs og sikre handovers globalt.",
      pros: [
        "Hurtigst over lange afstande — typisk 1–3 dage dør-til-dør",
        "Høj frekvens og global rækkevidde via major hubs",
        "Stabil tidsplan og stramme SLA’er",
        "Velegnet til højværdigt, temperaturfølsomt og hastegods",
        "Lav lagerbinding pga. kort transittid",
      ],
      cons: [
        "Højeste pris pr. kg blandt transportformerne",
        "Volumenvægt (chargeable weight) kan fordyre let/volumetungt gods",
        "Stramme sikkerhedsregler og screening",
        "Farligt gods (DG) har omfattende IATA-restriktioner",
      ],
      equipmentIntro: "Fra general cargo på ULD-paller til fuld charter, når der skal skrues helt op for tempo eller kapacitet.",
      equipment: [
        {
          id: "air-general",
          name: "General cargo",
          specs: "Stykgods på ULD-paller/containere · standard luftfragt",
          lead: "Grundlæggende luftfragt på rutefly — booket på faste afgange.",
          details: [
            ["Afgange", "Rutefly, dagligt på major hubs"],
            ["Transit", "Typisk 1–3 dage"],
            ["Booking", "Allocation eller spot"],
            ["Dokumenter", "Master/House AWB"],
          ],
          goodFor: ["Standard luftfragt", "Mellem-værdigt gods", "Ikke-tidskritiske hasteforsendelser"],
          notes: ["Cut-off typisk 4–8 timer før departure", "Screening kræves"],
        },
        {
          id: "air-priority",
          name: "Priority / Express",
          specs: "Øverste prioritet · hurtigste cut-off og første fly ud",
          lead: "Øverste prioritets-klasse — første om bord og første af.",
          details: [
            ["Prioritet", "Øverste serviceklasse"],
            ["Transit", "Typisk 24–48 timer"],
            ["Booking", "Garanteret space"],
            ["Tracking", "Milestones pr. handover"],
          ],
          goodFor: ["Kritiske reservedele", "Tidssensitiv pharma", "Højværdige hasteleverancer"],
          notes: ["Markant dyrere end general cargo", "Kræver klart cut-off-vindue"],
        },
        {
          id: "air-temp",
          name: "Temperature controlled",
          specs: "CRT/CFT-løsninger · pharma og perishables",
          lead: "Temperaturkontrolleret luftfragt — passive og aktive løsninger.",
          details: [
            ["Temperaturbånd", "+2/+8 °C · +15/+25 °C · CRT"],
            ["Udstyr", "Envirotainer, CSafe, thermocover"],
            ["Monitorering", "Datalogger, realtid via sensor"],
            ["Standarder", "GDP, IATA CEIV Pharma"],
          ],
          goodFor: ["Pharma og kliniske forsøg", "Food og perishables (blomster, fisk)", "Vaccine og biotek"],
          notes: ["Kræver certificeret håndtering end-to-end", "Booking tidligt for airside-ressourcer"],
        },
        {
          id: "air-dg",
          name: "Dangerous goods (DG)",
          specs: "IATA-certificeret håndtering · klasse 1–9 efter aftale",
          lead: "Farligt gods efter IATA DGR — korrekt klassificering er afgørende.",
          details: [
            ["Klasser", "1–9 (iht. IATA DGR)"],
            ["Dokumenter", "Shipper’s Declaration + MSDS"],
            ["Emballage", "UN-certificeret efter klasse/PG"],
            ["Restriktioner", "Pax/Cargo only varierer pr. stof"],
          ],
          goodFor: ["Kemi, lithium-batterier, aerosol", "Medicin-udstyr med fluid/li-ion", "Olie- og gas-reservedele"],
          notes: ["Fejl i klassificering stopper forsendelsen", "Ikke alle carriers accepterer alle klasser"],
        },
        {
          id: "air-charter",
          name: "Charter",
          specs: "Fuld maskine eller partial · projektlaster og hasteforsendelser",
          lead: "Fuld eller delvis charter — når rutefly ikke er nok.",
          details: [
            ["Typer", "Partial, Full, ACMI"],
            ["Flytyper", "Narrow-body til AN-124 (out-of-gauge)"],
            ["Rute", "Dør-til-dør efter behov"],
            ["Lead time", "Fra få timer ved AOG"],
          ],
          goodFor: ["AOG og nødsituationer", "Projekt-tungt/overhøjt gods", "Fuldladninger med én afsender"],
          notes: ["Omkostningstungt — kun for kritiske behov", "Luftrum/landingstilladelser skal koordineres"],
        },
        {
          id: "air-uld",
          name: "ULD-typer",
          specs: "PMC / PAG / AKE · tilpasses gods og flytype",
          lead: "Unit Load Device — container eller palle der passer direkte i flyet.",
          details: [
            ["PMC", "96×125\" pallet (main deck)"],
            ["PAG", "88×125\" pallet (main deck)"],
            ["AKE", "LD3 container (lower deck)"],
            ["AKN/AKH", "Øvrige standard lower-deck"],
          ],
          goodFor: ["Maksimal nyttelast pr. booking", "Mere effektiv stuvning", "Færre handling-risici pr. enhed"],
          notes: ["Gods skal passe indenfor ULD-dimensioner", "Kræver palletering og netting"],
        },
      ],
    },
    rail: {
      kicker: "04 · Rail",
      title: "Rail",
      lead: "Stærkt alternativ på udvalgte korridorer — stabil kapacitet og lavt CO₂-aftryk.",
      pros: [
        "God balance mellem pris og transit på etablerede korridorer",
        "Stabil kapacitet — mindre udsat for trafik og chaufførmangel",
        "Lavt CO₂-aftryk pr. ton-km",
        "Vejr-uafhængig fremdrift sammenlignet med vej og sø",
        "Stærk på bulk, containere og intermodale enheder",
      ],
      cons: [
        "Rute- og terminalafhængig frekvens",
        "Kræver næsten altid last-mile trucking",
        "Specialmål/-vægte kræver forhåndsplanlægning",
        "Færre direkte forbindelser end vej",
      ],
      equipmentIntro: "Intermodale containere på korridorer plus specialløsninger, når gods skal længere end et enkelt tog rækker.",
      equipment: [
        {
          id: "rail-intermodal",
          name: "40'/45' container intermodal",
          specs: "Standard container på togvogn · kombineret med last-mile truck",
          lead: "Container på tog — samme container fra fabrik til modtager med pre- og on-carriage på lastbil.",
          details: [
            ["Typer", "40' dry, HC, 45' pallet-wide"],
            ["Afgange", "Faste på EU-korridorer"],
            ["Transit", "2–7 dage afhængigt af rute"],
            ["Handover", "På multimodal terminal"],
          ],
          goodFor: ["Mellem-lange distancer i Europa", "CO₂-optimerede flow", "Stabil kapacitet uden chaufførafhængighed"],
          notes: ["Pre-/on-carriage på lastbil lægges på transit", "Terminal-tider påvirker dør-til-dør-plan"],
        },
        {
          id: "rail-20ft",
          name: "20' container intermodal",
          specs: "Til tunge eller densitetskrævende laster",
          lead: "20-fods på tog — perfekt til tunge laster hvor max-vægt er vigtigst.",
          details: [
            ["Læssevægt", "op til ~28.000 kg"],
            ["Volumen", "~33 m³"],
            ["Afgange", "På udvalgte korridorer"],
            ["Handover", "Multimodal terminal"],
          ],
          goodFor: ["Tung industriel last", "Stål, papir, maskinkomponenter", "Korte/mellemlange afstande"],
          notes: ["Mindre volumen end 40'", "Pre-/on-carriage nødvendig"],
        },
        {
          id: "rail-block",
          name: "Block train",
          specs: "Dedikeret fuldtog på fast korridor · høj volumen og faste afgange",
          lead: "Hele toget går samme vej — faste tider og maksimal kapacitet.",
          details: [
            ["Kapacitet", "~80–90 TEU pr. tog"],
            ["Afgange", "Faste ugentlige slots"],
            ["Operatør", "Fast ift. lokomotiv og vogne"],
            ["Handover", "Fast terminal i hver ende"],
          ],
          goodFor: ["Faste produktions- og eksportflow", "Store volumen-kunder", "Automotive, kemi og papir"],
          notes: ["Kræver volumen-aftaler", "Low spot-flexibilitet"],
        },
        {
          id: "rail-swap",
          name: "Swap body / trailer-on-train",
          specs: "Trailer eller skifteladvogn · nem overlevering til truck",
          lead: "Trailer eller skiftelad direkte på togvogn — minimerer håndtering.",
          details: [
            ["Typer", "P400 trailer, C745 swap body"],
            ["Afgange", "På kombi-korridorer"],
            ["Transit", "Sammenlignelig med road"],
            ["Handover", "Kombi-terminal"],
          ],
          goodFor: ["Når trailer skal fortsætte direkte på vej", "Kombi-terminal-til-kombi-terminal", "CO₂-reduktion på lange strækninger"],
          notes: ["Trailer skal være P400-godkendt", "Kombi-terminal-kapacitet styrer plan"],
        },
        {
          id: "rail-reefer",
          name: "Reefer rail",
          specs: "Temperaturstyret via gen-set · food og pharma på udvalgte ruter",
          lead: "Reefer-container på tog med gen-set — kølekæde uden opbrud.",
          details: [
            ["Temperatur", "−25 °C til +25 °C"],
            ["Strøm", "Gen-set eller on-board-power"],
            ["Monitorering", "Remote-logger"],
            ["Ruter", "Begrænset til udvalgte korridorer"],
          ],
          goodFor: ["Fødevarer på lange afstande", "Pharma på udvalgte ruter", "CO₂-optimeret kølekæde"],
          notes: ["Ikke på alle korridorer", "Gen-set-fuel skal håndteres"],
        },
        {
          id: "rail-special",
          name: "Specialvogne",
          specs: "Flat wagon, bogie wagon, heavy-duty · til overbredt og tungt gods",
          lead: "Åbne og specialdesignede togvogne til det helt ekstreme.",
          details: [
            ["Typer", "Flat, bogie, heavy-haul"],
            ["Læssevægt", "op til ~90.000 kg"],
            ["Profil", "OOG kan aftales"],
            ["Eskorte", "Inspektion ved af-/pålæsning"],
          ],
          goodFor: ["Tunge industrielementer", "Skinnetransport, vindmøllevinger", "Store præfab-emner"],
          notes: ["Lange lead times", "Kræver ruteplanlægning og tilladelser"],
        },
      ],
    },
  },

  en: {
    road: {
      kicker: "01 · Road",
      title: "Road",
      lead: "Flexible distribution across Europe — door-to-door with high frequency and reliable planning.",
      pros: [
        "Door-to-door without transhipment — low handling risk",
        "High frequency and short timelines from kick-off",
        "Wide equipment range from van to specialised trailers",
        "Strong on shorter and medium European stretches",
        "Easy to adapt if the plan changes underway",
      ],
      cons: [
        "Subject to driving/rest times, traffic and weather",
        "Limited capacity per unit (typically 24 t / 33 pallets)",
        "Higher CO₂ footprint per tonne-km than sea and rail",
        "Border controls and specialised cargo may require ADR/permits",
      ],
      equipmentIntro: "From standard 13.6 m curtain-sided trailers to special trailers for project cargo and heavy machinery.",
      equipment: [
        {
          id: "road-curtain",
          name: "Tractor + 13.6 m curtain-sided trailer",
          specs: "24,000 kg · 33 EUR pallets · tail lift/ADR",
          lead: "The workhorse of Europe — tarp open/closed; load/unload via side and rear.",
          details: [
            ["Internal dims", "13.60 × 2.47 × 3.10 m"],
            ["Payload", "up to 24,000 kg"],
            ["Pallets", "33 EUR pallets (single tier)"],
            ["Options", "Tail lift, ADR, coil-well on request"],
          ],
          goodFor: ["General cargo and full loads (LTL/FTL)", "Pallets, cartons, rolls and long items", "Side loading with forklift or crane"],
          notes: ["Height limits on bridges/tunnels on some routes", "Not temperature-controlled"],
        },
        {
          id: "road-solo18",
          name: "Rigid truck 18 t",
          specs: "7,000 kg · 23 EUR pallets · tail lift/ADR",
          lead: "Compact rigid for urban and medium distances — no semi-trailer coupling.",
          details: [
            ["Internal dims", "9.40 × 2.45 × 2.90 m"],
            ["Payload", "approx. 7,000 kg"],
            ["Pallets", "23 EUR pallets"],
            ["Options", "Tail lift, ADR"],
          ],
          goodFor: ["City-centre deliveries with space constraints", "Multi-stop distribution", "When a tail lift is required"],
          notes: ["Lower payload than semi-trailer", "Low-emission zone approval may apply in some cities"],
        },
        {
          id: "road-solo75",
          name: "Rigid truck 7.5 t",
          specs: "3,500 kg · 15 EUR pallets · tail lift/ADR",
          lead: "Light distribution vehicle — easy to manoeuvre; usually without special licences.",
          details: [
            ["Internal dims", "6.20 × 2.45 × 2.60 m"],
            ["Payload", "approx. 3,500 kg"],
            ["Pallets", "15 EUR pallets"],
            ["Options", "Tail lift, ADR"],
          ],
          goodFor: ["Fast urban distribution", "Small to medium shipments", "Narrow streets and tight collection points"],
          notes: ["Not ideal for very long or tall items"],
        },
        {
          id: "road-van",
          name: "Van 3.5 t",
          specs: "700–1,200 kg · 5–10 EUR pallets · tail lift/ADR",
          lead: "Agile and quick — suited to express and smaller consignments.",
          details: [
            ["Types", "Curtain 4.2–4.9 m · Box 3.85–4.70 m"],
            ["Height", "2.00–2.60 m internal"],
            ["Payload", "700–1,200 kg"],
            ["Pallets", "5–10 EUR pallets"],
          ],
          goodFor: ["Express and same-day runs", "Time-critical pharma and spare parts", "Dedicated direct drive"],
          notes: ["Limited capacity per vehicle"],
        },
        {
          id: "road-reefer",
          name: "Refrigerated / frozen trailer",
          specs: "22,000 kg · 13.6 × 2.45 × 2.65 m · temp-controlled · ADR",
          lead: "Temperature-controlled transport — from deep freeze to pharmaceutical windows.",
          details: [
            ["Internal dims", "13.60 × 2.45 × 2.65 m"],
            ["Temperature", "−25 °C to +25 °C"],
            ["Unit", "Diesel genset with monitoring"],
            ["Standards", "ATP, FRC/FNA as required by cargo"],
          ],
          goodFor: ["Food, pharmaceuticals, flowers", "Temperature-critical shipments", "Multi-temp partitions on request"],
          notes: ["Higher operating and fuel costs", "Requires an intact cold chain and documentation"],
        },
        {
          id: "road-platform",
          name: "Platform / flatbed",
          specs: "24,000 kg · 13.6 m · steel, containers and building materials",
          lead: "Open platform — load from all sides and from above with crane or forklift.",
          details: [
            ["Length", "13.60 m (standard)"],
            ["Payload", "up to 24,000 kg"],
            ["Equipment", "Steel coils, piles, powder handling"],
            ["Lashing", "Straps, chains, timber dunnage"],
          ],
          goodFor: ["Steel, pipes, containers, building materials", "Crane or side lift loading", "Wide loads with escort vehicle"],
          notes: ["No weather protection — packaging dependent"],
        },
        {
          id: "road-tiefbett",
          name: "Lowbed",
          specs: "38,000 kg · lowered deck · tall machinery and industrial units",
          lead: "Dropped deck for extra height — built for machinery and industrial components.",
          details: [
            ["Payload", "up to 38,000 kg"],
            ["Deck height", "approx. 0.85 m above road"],
            ["Extensions", "Detachable goosneck, width extensions"],
            ["Escort", "Pilot vehicle for out-of-gauge"],
          ],
          goodFor: ["Tall machinery, tanks, industrial elements", "Extremely heavy cargo", "Project and plant relocation"],
          notes: ["Permits and route planning are critical", "Time windows can be restrictive"],
        },
        {
          id: "road-semi",
          name: "Semi low-loader",
          specs: "28,000 kg · hydraulic ramps · excavators and heavy equipment",
          lead: "Low loader with hydraulic drive-on — load/unload in minutes.",
          details: [
            ["Payload", "up to 28,000 kg"],
            ["Ramps", "Hydraulic with winch"],
            ["Equipment", "Dunnage, lashing points"],
            ["Escort", "As required by cargo dimensions"],
          ],
          goodFor: ["Excavators, construction plant", "Vehicle and machinery on wheels", "Heavy equipment relocations"],
          notes: ["Some routes require advance approval"],
        },
        {
          id: "road-tele",
          name: "Extendable trailer (tele)",
          specs: "22,000 kg · extends up to 21 m · long items",
          lead: "Extendable trailer for long cargo — rails, mast sections, rotor blades.",
          details: [
            ["Length", "From 13.6 m up to 21 m"],
            ["Payload", "up to 22,000 kg"],
            ["Equipment", "Often steering axle for manoeuvring"],
            ["Escort", "Pilot and security vehicles"],
          ],
          goodFor: ["Wind blades, poles, rails", "Long prefabricated elements", "Project cargo"],
          notes: ["Large turning radius — network constraints"],
        },
      ],
    },
    sea: {
      kicker: "02 · Sea",
      title: "Sea",
      lead: "Robust and cost-effective for volume — FCL, LCL and special containers.",
      pros: [
        "Lowest cost per tonne for volume and long distances",
        "Global capacity and services to virtually all markets",
        "Solutions for out-of-gauge, tall, heavy and temperature-controlled cargo",
        "Low CO₂ footprint per tonne-km",
        "Scales from LCL general cargo to full-container FCL",
      ],
      cons: [
        "Long transit — often weeks rather than days",
        "Strict cut-offs and documentation before sailing",
        "ETA variability due to weather, ports and berth capacity",
        "Special cargo requires correct stowage and packing",
      ],
      equipmentIntro: "We book and coordinate all standard container types — and source special equipment when a box will not fit.",
      equipment: [
        {
          id: "sea-dry20",
          name: "20' dry container",
          specs: "Int. approx. 5.9 × 2.35 × 2.39 m · ~28 t · general dry",
          lead: "Standard 20-ft container — the FCL staple.",
          details: [
            ["Internal dims", "5.90 × 2.35 × 2.39 m"],
            ["Door opening", "2.34 × 2.28 m"],
            ["Max payload", "~28,000 kg (route-dependent)"],
            ["Volume", "~33 m³"],
          ],
          goodFor: ["Heavy, dense-stowed cargo", "Full container loads (FCL)", "Dry cargo without climate needs"],
          notes: ["Lower cube than 40'", "Not suited to over-height cargo"],
        },
        {
          id: "sea-dry40",
          name: "40' dry container",
          specs: "Int. approx. 12.03 × 2.35 × 2.39 m · ~28 t · general dry",
          lead: "Double the length — best when cube matters more than weight.",
          details: [
            ["Internal dims", "12.03 × 2.35 × 2.39 m"],
            ["Door opening", "2.34 × 2.28 m"],
            ["Max payload", "~28,000 kg"],
            ["Volume", "~67 m³"],
          ],
          goodFor: ["Bulky/lightweight cargoes", "Furniture, textiles, non-food", "Full container loads (FCL)"],
          notes: ["Same height as 20' dry — not for over-height"],
        },
        {
          id: "sea-hc",
          name: "40' high cube (HC)",
          specs: "Extra internal height 2.69 m · high-cube freight",
          lead: "Same footprint as 40' dry — extra height for volume.",
          details: [
            ["Internal height", "2.69 m (vs 2.39 m standard)"],
            ["Internal length/width", "12.03 × 2.35 m"],
            ["Max payload", "~28,000 kg"],
            ["Volume", "~76 m³"],
          ],
          goodFor: ["Light and voluminous loads", "Tall cargo up to 2.69 m", "Furniture, foam, insulation"],
          notes: ["Height limits on inland moves to/from port"],
        },
        {
          id: "sea-reefer",
          name: "Reefer 20'/40'",
          specs: "Temp-controlled −30 °C to +30 °C · pharma, food, perishables",
          lead: "Temperature-controlled reefers — from deep freeze to pharmaceutical bands.",
          details: [
            ["Temperature", "−30 °C to +30 °C"],
            ["Internal dims 40' HC reefer", "11.56 × 2.29 × 2.56 m"],
            ["Power", "On-board or shore plug-in"],
            ["Monitoring", "Data logger and alarms"],
          ],
          goodFor: ["Fruit, vegetables, fish, meat", "Pharma and life sciences", "Temperature-critical chemicals"],
          notes: ["Shore plug-in slots must be booked", "Requires an intact cold chain"],
        },
        {
          id: "sea-opentop",
          name: "Open top",
          specs: "Open top with tarp · over-height cargo and top loading",
          lead: "No fixed roof — load from above with crane; tarp system as weather cover.",
          details: [
            ["Internal dims 40'", "12.03 × 2.35 × 2.35 m"],
            ["Roof", "Tarpaulin system with bows"],
            ["Max payload", "~28,000 kg"],
            ["Extra height", "Over-height on request"],
          ],
          goodFor: ["Machinery and over-height cargo", "Crane lift directly into the box", "Cargo that cannot load through the doors"],
          notes: ["Weather exposure without a solid roof", "May require over-dimension approvals"],
        },
        {
          id: "sea-flatrack",
          name: "Flat rack",
          specs: "No sides/roof · out-of-gauge cargo, machinery and steel",
          lead: "Platform with end walls — collapsible sides; limited only by weight and securing.",
          details: [
            ["Standard lengths", "20' and 40'"],
            ["Max payload", "up to 40,000 kg (40')"],
            ["Lashing", "Straps, chains integrated in deck"],
            ["End walls", "Fold flat for over-length"],
          ],
          goodFor: ["Extra width and length", "Vehicle carriage, machinery, pipe, steel", "Crane in/out at port"],
          notes: ["No weather protection", "Lashing is critical"],
        },
        {
          id: "sea-platform",
          name: "Platform",
          specs: "Flat deck without ends · very long or heavy cargo",
          lead: "Fully flat deck with no sides or endwalls — only for cargo that fits nowhere else.",
          details: [
            ["Lengths", "20' and 40'"],
            ["Max payload", "Up to 40,000 kg"],
            ["Form factor", "Flat — no ends, no sides"],
            ["Lashing", "All perimeter points"],
          ],
          goodFor: ["Extremely heavy/long cargo", "Industrial components", "Project and plant moves"],
          notes: ["Booked as out-of-gauge (OOG)", "Requires level-matched ship stowage"],
        },
        {
          id: "sea-goh",
          name: "GOH (garments on hangers)",
          specs: "Integrated hanger system · apparel without repacking",
          lead: "40' with built-in hanger system — garments arrive shop-ready from mill to store.",
          details: [
            ["Capacity", "up to roughly 10,000–14,000 garments"],
            ["System", "Fixed/mobile bars along the ceiling"],
            ["Securing", "Dedicated hangers and covers"],
            ["Base", "40' dry or HC"],
          ],
          goodFor: ["Fashion and apparel", "High-end brands without repacking", "Direct retail delivery"],
          notes: ["Higher freight cost per kg than standard", "Only select operators offer GOH"],
        },
      ],
    },
    air: {
      kicker: "03 · Air",
      title: "Air",
      lead: "When time is critical — fast departures, cut-offs and secure handovers worldwide.",
      pros: [
        "Fastest over long distances — typically 1–3 days door-to-door",
        "High frequency and global reach via major hubs",
        "Stable schedules and tight SLAs",
        "Suited to high-value, temperature-sensitive and urgent cargo",
        "Low inventory tied up owing to short transit",
      ],
      cons: [
        "Highest price per kg across modes",
        "Chargeable weight can make light/bulky cargo expensive",
        "Strict security rules and screening",
        "Dangerous goods (DG) face extensive IATA restrictions",
      ],
      equipmentIntro: "From general cargo on ULD pallets to full charter when you need maximum speed or capacity.",
      equipment: [
        {
          id: "air-general",
          name: "General cargo",
          specs: "Loose/load on ULD pallets/containers · standard air freight",
          lead: "Core air freight on scheduled flights — booked on fixed departures.",
          details: [
            ["Departures", "Scheduled, daily from major hubs"],
            ["Transit", "Typically 1–3 days"],
            ["Booking", "Allocation or spot"],
            ["Documents", "Master/House AWB"],
          ],
          goodFor: ["Standard air freight", "Medium-value cargo", "Urgent but not ultra time-critical shipments"],
          notes: ["Cut-off typically 4–8 hours before departure", "Screening mandatory"],
        },
        {
          id: "air-priority",
          name: "Priority / express",
          specs: "Top priority · earliest cut-off and first flight out",
          lead: "Highest service tier — first on board and first off.",
          details: [
            ["Priority", "Top service class"],
            ["Transit", "Typically 24–48 hours"],
            ["Booking", "Guaranteed space"],
            ["Tracking", "Milestones per handover"],
          ],
          goodFor: ["Critical spare parts", "Time-sensitive pharma", "High-value express deliveries"],
          notes: ["Significantly more expensive than general cargo", "Needs a clearly defined cut-off window"],
        },
        {
          id: "air-temp",
          name: "Temperature controlled",
          specs: "CRT/CFT solutions · pharma and perishables",
          lead: "Temperature-controlled air freight — passive and active solutions.",
          details: [
            ["Temperature bands", "+2/+8 °C · +15/+25 °C · CRT"],
            ["Equipment", "Envirotainer, CSafe, thermal covers"],
            ["Monitoring", "Data logger; real-time sensors"],
            ["Standards", "GDP, IATA CEIV Pharma"],
          ],
          goodFor: ["Pharma and clinical trials", "Food and perishables (flowers, fish)", "Vaccines and biotech"],
          notes: ["Requires certified handling end-to-end", "Book early for airside resources"],
        },
        {
          id: "air-dg",
          name: "Dangerous goods (DG)",
          specs: "IATA-certified handling · classes 1–9 subject to acceptance",
          lead: "Dangerous goods under IATA DGR — accurate classification is essential.",
          details: [
            ["Classes", "1–9 per IATA DGR"],
            ["Documents", "Shipper's declaration + SDS/MSDS"],
            ["Packaging", "UN-approved per class/PG"],
            ["Restrictions", "Pax vs cargo-only varies by substance"],
          ],
          goodFor: ["Chemicals, lithium batteries, aerosols", "Medical devices with fluids/Li-ion", "Oil & gas spare parts"],
          notes: ["Misclassification stops the shipment", "Not every carrier accepts every class"],
        },
        {
          id: "air-charter",
          name: "Charter",
          specs: "Full aircraft or partial · project lifts and emergencies",
          lead: "Full or partial charter — when scheduled capacity is not enough.",
          details: [
            ["Types", "Partial, full, ACMI"],
            ["Aircraft types", "Narrow-body through AN-124 (out-of-gauge)"],
            ["Routing", "Door-to-door as required"],
            ["Lead time", "From hours in AOG cases"],
          ],
          goodFor: ["Aircraft on ground (AOG) and emergencies", "Heavy or out-of-gauge project cargo", "Full loads from a single shipper"],
          notes: ["Cost-intensive — for critical needs only", "Airspace and landing permissions must be coordinated"],
        },
        {
          id: "air-uld",
          name: "ULD types",
          specs: "PMC / PAG / AKE · matched to cargo and aircraft",
          lead: "Unit load device — container or pallet that interfaces directly with the aircraft.",
          details: [
            ["PMC", "96×125\" pallet (main deck)"],
            ["PAG", "88×125\" pallet (main deck)"],
            ["AKE", "LD3 container (lower deck)"],
            ["AKN/AKH", "Other standard lower-deck ULDs"],
          ],
          goodFor: ["Maximum payload per booking", "More efficient stowage", "Fewer handling risks per unit"],
          notes: ["Cargo must fit ULD dimensions", "Requires build-up and netting"],
        },
      ],
    },
    rail: {
      kicker: "04 · Rail",
      title: "Rail",
      lead: "A strong option on selected corridors — stable capacity and low CO₂ footprint.",
      pros: [
        "Good balance of price and transit on established corridors",
        "Stable capacity — less exposed to traffic and driver shortages",
        "Low CO₂ footprint per tonne-km",
        "Less weather-sensitive than road and sea",
        "Strong for bulk, containers and intermodal units",
      ],
      cons: [
        "Frequency depends on route and terminal",
        "Almost always needs last-mile trucking",
        "Out-of-gauge/heavy loads need advance planning",
        "Fewer direct connections than road",
      ],
      equipmentIntro: "Intermodal containers on corridors plus special solutions when one train is not enough.",
      equipment: [
        {
          id: "rail-intermodal",
          name: "40'/45' intermodal container",
          specs: "Standard box on rail wagon · with last-mile truck",
          lead: "Container on rail — same box from shipper to consignee with road pre- and on-carriage.",
          details: [
            ["Types", "40' dry, HC, 45' pallet-wide"],
            ["Departures", "Fixed slots on EU corridors"],
            ["Transit", "2–7 days depending on lane"],
            ["Handover", "At multimodal terminal"],
          ],
          goodFor: ["Medium–long distances in Europe", "CO₂-optimised flows", "Stable capacity without driver dependency"],
          notes: ["Road pre-/on-carriage adds to overall transit", "Terminal windows affect door-to-door planning"],
        },
        {
          id: "rail-20ft",
          name: "20' intermodal container",
          specs: "For heavy or density-driven loads",
          lead: "20-ft on rail — ideal when maximum weight matters most.",
          details: [
            ["Payload", "up to ~28,000 kg"],
            ["Volume", "~33 m³"],
            ["Departures", "On selected corridors"],
            ["Handover", "Multimodal terminal"],
          ],
          goodFor: ["Heavy industrial freight", "Steel, paper, machinery parts", "Short/medium distances"],
          notes: ["Less cube than 40'", "Pre-/on-carriage required"],
        },
        {
          id: "rail-block",
          name: "Block train",
          specs: "Dedicated full train on a fixed corridor · high volume, fixed departures",
          lead: "The whole train runs one route — fixed paths and maximum capacity.",
          details: [
            ["Capacity", "~80–90 TEU per train"],
            ["Departures", "Fixed weekly slots"],
            ["Operator", "Dedicated locomotive and wagons"],
            ["Handover", "Fixed terminal at each end"],
          ],
          goodFor: ["Steady production and export flows", "High-volume customers", "Automotive, chemicals and paper"],
          notes: ["Requires volume commitments", "Limited spot flexibility"],
        },
        {
          id: "rail-swap",
          name: "Swap body / trailer-on-train",
          specs: "Trailer or swap body · easy handover to truck",
          lead: "Trailer or swap body on the wagon — minimal handling.",
          details: [
            ["Types", "P400 trailer, C745 swap body"],
            ["Departures", "On combi corridors"],
            ["Transit", "Comparable to road"],
            ["Handover", "Combi terminal"],
          ],
          goodFor: ["When the trailer continues straight on road", "Terminal-to-terminal combi", "CO₂ reduction on long legs"],
          notes: ["Trailer must be P400-approved", "Combi terminal capacity drives planning"],
        },
        {
          id: "rail-reefer",
          name: "Reefer rail",
          specs: "Temperature-controlled via gen-set · food and pharma on select routes",
          lead: "Reefer container on rail with genset — cold chain without break.",
          details: [
            ["Temperature", "−25 °C to +25 °C"],
            ["Power", "Genset or on-board supply"],
            ["Monitoring", "Remote data logger"],
            ["Routes", "Limited to selected corridors"],
          ],
          goodFor: ["Food over long distances", "Pharma on approved lanes", "CO₂-optimised cold chain"],
          notes: ["Not available on every corridor", "Genset fuel must be managed"],
        },
        {
          id: "rail-special",
          name: "Special wagons",
          specs: "Flat wagon, bogie wagon, heavy-duty · out-of-gauge and heavy cargo",
          lead: "Open and purpose-built wagons for the extremes.",
          details: [
            ["Types", "Flat, bogie, heavy-haul"],
            ["Payload", "up to ~90,000 kg"],
            ["Profile", "OOG arrangements on request"],
            ["Escort", "Inspection at load/unload"],
          ],
          goodFor: ["Heavy industrial elements", "Rail transport sections, wind blades", "Large prefabricated pieces"],
          notes: ["Long lead times", "Requires route engineering and permits"],
        },
      ],
    },
  },
};
